### ISSUE TITLE
CUDA nvcc에서 32-bit 빌드 컴파일 미지원

### ISSUE THREAD

**Issue by unta1337** [unta1337/Multi-Segmenter#48]
쿠다 컴파일러 nvcc에서 x86 빌드를 미지원함에 따라 CMake 관련 설정을 아래와 같이 변경해야 할 수 있음.
(CUDA 버전 9.0 이후로 x86는 Deprecated되어 제거되는 추세, 현재 최신 CUDA 버전은 12 이상.)

![image](https://github.com/unta1337/Multi-Segmenter/assets/51486948/3d67f094-2566-4c9b-9183-1222327ac1d4)

1안:
기존 OpenMP 버전과 CUDA 버전을 한 번에 빌드하지만 OpenMP 버전의 x86 빌드 제거

2안:
기존 OpenMP 버전과 CUDA 버전을 따로 빌드하여 OpenMP 버전은 x86, x64 모두, CUDA 버전은 x64만 빌드

ref: https://forums.developer.nvidia.com/t/cuda-9-0-nvcc-does-not-support-compiling-cuda-code-inside-32-bit-projects-on-visual-studio-2015/54950

**Comment by refracta** [comment]
이제 모든 플랫폼에서 x86 빌드를 지원하지 않음
